sudo: required
services:
    - docker

before_install:
    - docker build -t gamerited/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true gamerited/docker-react npm run test

deploy:
    provider: elsaticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-310253773816"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key:
        secure: "$AWS_SECRET_KEY"

        

