sudo: required
services:
    - docker

before_install:
    - docker build -t gamerited/docker-react -f Dockerfile.dev . 

script:
    - docker run -i gamerited/docker-react npm run test -- --coverage


